import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  UserButton,
} from "@clerk/nextjs";
import { Doto } from "next/font/google";
import "./globals.scss";

const doto = Doto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-doto",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${doto.variable} antialiased`}>
        <ClerkProvider>
          <Show when="signed-in">
            <header className="flex h-16 items-center justify-end p-4">
              <UserButton />
            </header>
          </Show>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
